
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE servlet2_db;" -U postgres
  - psql -c "CREATE USER webtester WITH PASSWORD '1234';" -U postgres
# - psql -c 'CREATE SCHEMA "Moo" AUTHORIZATION migrator;' -U postgres -d migrations
  - dotnet restore
script:
  - dotnet test ./ThinkingHome.Migrator.Tests -c Release -f netcoreapp2.0
language: java




notifications:
  email:
    recipients:
      - borninger@yandex.ru
    on_success: always
    on_failure: always